// <auto-generated />
using System;
using BandBlend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BandBlend2.Migrations
{
    [DbContext(typeof(BandBlendDbContext))]
    [Migration("20231110000742_initCreate")]
    partial class initCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BandBlend.Models.AdditionalPicture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AdditionalPictures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Url = "https://images.unsplash.com/photo-1516122276289-c28ffbaf888c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1287&q=80",
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 2,
                            Url = "https://images.unsplash.com/photo-1516122276289-c28ffbaf888c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1287&q=80",
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 3,
                            Url = "https://images.unsplash.com/photo-1516122276289-c28ffbaf888c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1287&q=80",
                            UserProfileId = 2
                        });
                });

            modelBuilder.Entity("BandBlend.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Date = new DateTime(2023, 11, 6, 12, 5, 0, 0, DateTimeKind.Unspecified),
                            PostId = 1,
                            UserProfileId = 2
                        });
                });

            modelBuilder.Entity("BandBlend.Models.Like", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Likes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2023, 11, 6, 12, 18, 0, 0, DateTimeKind.Unspecified),
                            PostId = 1,
                            UserProfileId = 2
                        });
                });

            modelBuilder.Entity("BandBlend.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("integer");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Date = new DateTime(2023, 11, 6, 12, 5, 0, 0, DateTimeKind.Unspecified),
                            IsRead = false,
                            ReceiverId = 2,
                            SenderId = 1
                        },
                        new
                        {
                            Id = 2,
                            Body = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Date = new DateTime(2023, 11, 6, 12, 6, 0, 0, DateTimeKind.Unspecified),
                            IsRead = false,
                            ReceiverId = 1,
                            SenderId = 2
                        });
                });

            modelBuilder.Entity("BandBlend.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Date = new DateTime(2023, 11, 6, 12, 2, 0, 0, DateTimeKind.Unspecified),
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 2,
                            Body = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Date = new DateTime(2023, 11, 6, 12, 3, 0, 0, DateTimeKind.Unspecified),
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 3,
                            Body = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Date = new DateTime(2023, 11, 6, 12, 2, 0, 0, DateTimeKind.Unspecified),
                            UserProfileId = 2
                        });
                });

            modelBuilder.Entity("BandBlend.Models.PrimaryGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PrimaryGenres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Rock"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Alternative"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Blues"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Classical"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Country"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Electronic"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Folk"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Hip-Hop"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Indie"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Jazz"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Metal"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Pop"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Punk"
                        },
                        new
                        {
                            Id = 14,
                            Name = "R&B"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Rap"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Reggae"
                        });
                });

            modelBuilder.Entity("BandBlend.Models.PrimaryInstrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PrimaryInstruments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Acoustic Guitar"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Electric Guitar"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bass"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Drums"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Violin"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Saxophone"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Keyboard"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Piano"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Trumpet"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Flute"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Steel Drum"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Harp"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Trombone"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Clarinet"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Vocals"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Other"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Band"
                        });
                });

            modelBuilder.Entity("BandBlend.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("FacebookLink")
                        .HasColumnType("text");

                    b.Property<string>("InstagramLink")
                        .HasColumnType("text");

                    b.Property<int>("PrimaryGenreId")
                        .HasColumnType("integer");

                    b.Property<int?>("PrimaryInstrumentId")
                        .HasColumnType("integer");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("text");

                    b.Property<string>("SpotifyLink")
                        .HasColumnType("text");

                    b.Property<int>("StateId")
                        .HasColumnType("integer");

                    b.Property<string>("TikTokLink")
                        .HasColumnType("text");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryGenreId");

                    b.HasIndex("PrimaryInstrumentId");

                    b.HasIndex("StateId");

                    b.HasIndex("UserProfileId")
                        .IsUnique();

                    b.ToTable("Profiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            About = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            City = "Nashville",
                            FacebookLink = "https://www.facebook.com/joshbaughmusic/",
                            InstagramLink = "https://www.instagram.com/joshbaughmusic/",
                            PrimaryGenreId = 1,
                            PrimaryInstrumentId = 1,
                            ProfilePicture = "https://images.unsplash.com/photo-1516122276289-c28ffbaf888c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1287&q=80",
                            StateId = 42,
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 2,
                            About = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            City = "Somewhere",
                            FacebookLink = "https://www.facebook.com/joshbaughmusic/",
                            InstagramLink = "https://www.instagram.com/joshbaughmusic/",
                            PrimaryGenreId = 2,
                            PrimaryInstrumentId = 2,
                            ProfilePicture = "https://images.unsplash.com/photo-1516122276289-c28ffbaf888c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1287&q=80",
                            SpotifyLink = "https://www.facebook.com/joshbaughmusic/",
                            StateId = 40,
                            TikTokLink = "https://www.facebook.com/joshbaughmusic/",
                            UserProfileId = 2
                        });
                });

            modelBuilder.Entity("BandBlend.Models.ProfileSubGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProfileId")
                        .HasColumnType("integer");

                    b.Property<int>("SubGenreId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("SubGenreId");

                    b.ToTable("ProfileSubGenres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProfileId = 1,
                            SubGenreId = 2
                        },
                        new
                        {
                            Id = 2,
                            ProfileId = 1,
                            SubGenreId = 3
                        },
                        new
                        {
                            Id = 3,
                            ProfileId = 1,
                            SubGenreId = 1
                        },
                        new
                        {
                            Id = 4,
                            ProfileId = 2,
                            SubGenreId = 4
                        },
                        new
                        {
                            Id = 5,
                            ProfileId = 2,
                            SubGenreId = 5
                        },
                        new
                        {
                            Id = 6,
                            ProfileId = 2,
                            SubGenreId = 6
                        });
                });

            modelBuilder.Entity("BandBlend.Models.ProfileTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProfileId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("TagId");

                    b.ToTable("ProfileTags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProfileId = 1,
                            TagId = 2
                        },
                        new
                        {
                            Id = 2,
                            ProfileId = 1,
                            TagId = 3
                        },
                        new
                        {
                            Id = 3,
                            ProfileId = 1,
                            TagId = 1
                        },
                        new
                        {
                            Id = 4,
                            ProfileId = 2,
                            TagId = 4
                        },
                        new
                        {
                            Id = 5,
                            ProfileId = 2,
                            TagId = 5
                        },
                        new
                        {
                            Id = 6,
                            ProfileId = 2,
                            TagId = 6
                        });
                });

            modelBuilder.Entity("BandBlend.Models.SavedProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProfileId")
                        .HasColumnType("integer");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("SavedProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProfileId = 2,
                            UserProfileId = 1
                        });
                });

            modelBuilder.Entity("BandBlend.Models.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "AL"
                        },
                        new
                        {
                            Id = 2,
                            Name = "AK"
                        },
                        new
                        {
                            Id = 3,
                            Name = "AZ"
                        },
                        new
                        {
                            Id = 4,
                            Name = "AR"
                        },
                        new
                        {
                            Id = 5,
                            Name = "CA"
                        },
                        new
                        {
                            Id = 6,
                            Name = "CO"
                        },
                        new
                        {
                            Id = 7,
                            Name = "CT"
                        },
                        new
                        {
                            Id = 8,
                            Name = "DE"
                        },
                        new
                        {
                            Id = 9,
                            Name = "FL"
                        },
                        new
                        {
                            Id = 10,
                            Name = "GA"
                        },
                        new
                        {
                            Id = 11,
                            Name = "HI"
                        },
                        new
                        {
                            Id = 12,
                            Name = "ID"
                        },
                        new
                        {
                            Id = 13,
                            Name = "IL"
                        },
                        new
                        {
                            Id = 14,
                            Name = "IN"
                        },
                        new
                        {
                            Id = 15,
                            Name = "IA"
                        },
                        new
                        {
                            Id = 16,
                            Name = "KS"
                        },
                        new
                        {
                            Id = 17,
                            Name = "KY"
                        },
                        new
                        {
                            Id = 18,
                            Name = "LA"
                        },
                        new
                        {
                            Id = 19,
                            Name = "ME"
                        },
                        new
                        {
                            Id = 20,
                            Name = "MD"
                        },
                        new
                        {
                            Id = 21,
                            Name = "MA"
                        },
                        new
                        {
                            Id = 22,
                            Name = "MI"
                        },
                        new
                        {
                            Id = 23,
                            Name = "MN"
                        },
                        new
                        {
                            Id = 24,
                            Name = "MS"
                        },
                        new
                        {
                            Id = 25,
                            Name = "MO"
                        },
                        new
                        {
                            Id = 26,
                            Name = "MT"
                        },
                        new
                        {
                            Id = 27,
                            Name = "NE"
                        },
                        new
                        {
                            Id = 28,
                            Name = "NV"
                        },
                        new
                        {
                            Id = 29,
                            Name = "NH"
                        },
                        new
                        {
                            Id = 30,
                            Name = "NJ"
                        },
                        new
                        {
                            Id = 31,
                            Name = "NM"
                        },
                        new
                        {
                            Id = 32,
                            Name = "NY"
                        },
                        new
                        {
                            Id = 33,
                            Name = "NC"
                        },
                        new
                        {
                            Id = 34,
                            Name = "ND"
                        },
                        new
                        {
                            Id = 35,
                            Name = "OH"
                        },
                        new
                        {
                            Id = 36,
                            Name = "OK"
                        },
                        new
                        {
                            Id = 37,
                            Name = "OR"
                        },
                        new
                        {
                            Id = 38,
                            Name = "PA"
                        },
                        new
                        {
                            Id = 39,
                            Name = "RI"
                        },
                        new
                        {
                            Id = 40,
                            Name = "SC"
                        },
                        new
                        {
                            Id = 41,
                            Name = "SD"
                        },
                        new
                        {
                            Id = 42,
                            Name = "TN"
                        },
                        new
                        {
                            Id = 43,
                            Name = "TX"
                        },
                        new
                        {
                            Id = 44,
                            Name = "UT"
                        },
                        new
                        {
                            Id = 45,
                            Name = "VT"
                        },
                        new
                        {
                            Id = 46,
                            Name = "VA"
                        },
                        new
                        {
                            Id = 47,
                            Name = "WA"
                        },
                        new
                        {
                            Id = 48,
                            Name = "WV"
                        },
                        new
                        {
                            Id = 49,
                            Name = "WI"
                        },
                        new
                        {
                            Id = 50,
                            Name = "WY"
                        });
                });

            modelBuilder.Entity("BandBlend.Models.SubGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SubGenres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Acoustic Folk"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Alternative Rock"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Baroque"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Chicago Blues"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Classic Rock"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Contemporary R&B"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Country Pop"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Dance Pop"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Deathcore"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Delta Blues"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Dream Pop"
                        },
                        new
                        {
                            Id = 12,
                            Name = "East Coast Hip-Hop"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Fusion Jazz"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Glam Rock"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Grunge"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Hard Rock"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Hardcore Punk"
                        },
                        new
                        {
                            Id = 18,
                            Name = "House"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Indie Folk"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Indie Pop"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Melodic Death Metal"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Metalcore"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Motown"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Neo-Soul"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Nu Metal"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Pop Punk"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Pop Rock"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Post-Punk"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Progressive Metal"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Punk"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Smooth Jazz"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Street Punk"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Synth-pop"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Techno"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Thrash Metal"
                        },
                        new
                        {
                            Id = 36,
                            Name = "West Coast Hip-Hop"
                        });
                });

            modelBuilder.Entity("BandBlend.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Hobbyist"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Professional"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Weekend Warrior"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Paying Gigs Only"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Passion First"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Serious"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Casual"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Collaborative"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Songwriter"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Versatile"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Session Musician"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Touring"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Recording"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Studio Musician"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Beginner Friendly"
                        });
                });

            modelBuilder.Entity("BandBlend.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("text");

                    b.Property<bool>("IsBand")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdentityUserId = "dbc40bc6-0829-4ac5-a3ed-180f5e916a5f",
                            IsBand = false,
                            Name = "Josh Baugh"
                        },
                        new
                        {
                            Id = 2,
                            IdentityUserId = "7f4e6f8d-71ef-4b38-9aa1-6e39e4ec7c73",
                            IsBand = false,
                            Name = "Tom Jones"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "c3aaeb97-d2ba-4a53-a521-4eea61e59b35",
                            Name = "Admin",
                            NormalizedName = "admin"
                        },
                        new
                        {
                            Id = "d13f78a0-531c-4ae4-92d6-e1ea9fdd7d63",
                            Name = "User",
                            NormalizedName = "user"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "dbc40bc6-0829-4ac5-a3ed-180f5e916a5f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bc9635e9-4bc6-474a-9df1-f5477e848ee1",
                            Email = "josh@bandblend.comx",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEL9REHbY1rRohKbcMrDHMi+C6LuLHzjQVssVHzOvxKiFp1J893pi/jkWp66d8yduEA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1e31a533-cae8-4e54-a04a-1a91e57693ec",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "7f4e6f8d-71ef-4b38-9aa1-6e39e4ec7c73",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0e1ded61-d3f4-45c7-9011-6d7301aa3c00",
                            Email = "tom@bandblend.comx",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEMccK3H3gPO+95SUlVzGDHs4m5WbvsdWe4NWktTPR+mbs/qUzYXvmR05cMm7/5ev8w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8f95bf40-3aac-4ae1-b9f0-6f2703734b84",
                            TwoFactorEnabled = false
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "dbc40bc6-0829-4ac5-a3ed-180f5e916a5f",
                            RoleId = "c3aaeb97-d2ba-4a53-a521-4eea61e59b35"
                        },
                        new
                        {
                            UserId = "7f4e6f8d-71ef-4b38-9aa1-6e39e4ec7c73",
                            RoleId = "d13f78a0-531c-4ae4-92d6-e1ea9fdd7d63"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BandBlend.Models.Comment", b =>
                {
                    b.HasOne("BandBlend.Models.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BandBlend.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("BandBlend.Models.Like", b =>
                {
                    b.HasOne("BandBlend.Models.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BandBlend.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("BandBlend.Models.Message", b =>
                {
                    b.HasOne("BandBlend.Models.Profile", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BandBlend.Models.Profile", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("BandBlend.Models.Post", b =>
                {
                    b.HasOne("BandBlend.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("BandBlend.Models.Profile", b =>
                {
                    b.HasOne("BandBlend.Models.PrimaryGenre", "PrimaryGenre")
                        .WithMany()
                        .HasForeignKey("PrimaryGenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BandBlend.Models.PrimaryInstrument", "PrimaryInstrument")
                        .WithMany()
                        .HasForeignKey("PrimaryInstrumentId");

                    b.HasOne("BandBlend.Models.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BandBlend.Models.UserProfile", "UserProfile")
                        .WithOne("Profile")
                        .HasForeignKey("BandBlend.Models.Profile", "UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrimaryGenre");

                    b.Navigation("PrimaryInstrument");

                    b.Navigation("State");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("BandBlend.Models.ProfileSubGenre", b =>
                {
                    b.HasOne("BandBlend.Models.Profile", "Profile")
                        .WithMany("ProfileSubGenres")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BandBlend.Models.SubGenre", "SubGenre")
                        .WithMany()
                        .HasForeignKey("SubGenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("SubGenre");
                });

            modelBuilder.Entity("BandBlend.Models.ProfileTag", b =>
                {
                    b.HasOne("BandBlend.Models.Profile", "Profile")
                        .WithMany("ProfileTags")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BandBlend.Models.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("BandBlend.Models.SavedProfile", b =>
                {
                    b.HasOne("BandBlend.Models.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BandBlend.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("BandBlend.Models.UserProfile", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId");

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BandBlend.Models.Profile", b =>
                {
                    b.Navigation("ProfileSubGenres");

                    b.Navigation("ProfileTags");
                });

            modelBuilder.Entity("BandBlend.Models.UserProfile", b =>
                {
                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
